version: '3.8'

services:
  bge-service:
    build:
      context: ../../..
      dockerfile: infrastructure/docker/bge-service/Dockerfile
    container_name: revops-bge-service
    restart: unless-stopped
    
    # Environment Variables
    environment:
      - BGE_MODEL_PATH=/app/models/bge-m3
      - BGE_SERVICE_PORT=8007
      - LOG_LEVEL=info
      - MAX_BATCH_SIZE=32
      - PYTHONUNBUFFERED=1
    
    # Port Mapping
    ports:
      - "8007:8007"
    
    # Volume Mounts
    volumes:
      # Mount BGE models (already downloaded)
      - ./models:/app/models:ro
      # Mount logs directory  
      - ./infrastructure/docker/bge-service/logs:/app/logs:rw
      # Mount cache directory
      - ./infrastructure/docker/bge-service/cache:/app/cache:rw
    
    # Health Check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8007/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Network Configuration
    networks:
      - revops-network
    
    # Logging Configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Resource Limits
    mem_limit: 4g
    memswap_limit: 4g

# Network Configuration
networks:
  revops-network:
    driver: bridge
    name: revops-network

# Volume Configuration (if needed for persistent storage)
volumes:
  bge-models:
    driver: local
  bge-cache:
    driver: local
  bge-logs:
    driver: local